{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0eab28bf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "import random\n",
    "\n",
    "DAYS_PER_YEAR = 252\n",
    "DAYS_PER_WEEK = 5\n",
    "STEPS_PER_DAY = 4\n",
    "\n",
    "def simulate_prices(days: int):\n",
    "    prices_len = STEPS_PER_DAY * days\n",
    "    prices = [50]\n",
    "    dt = 1 / (DAYS_PER_YEAR * STEPS_PER_DAY)\n",
    "    sigma = 2.51  # 251% volatility\n",
    "    for _ in range(prices_len):\n",
    "        z = random.gauss(0, 1)\n",
    "        # GBM step with zero drift\n",
    "        prev = prices[-1]\n",
    "        next_price = prev * math.exp(-0.5 * sigma**2 * dt + sigma * math.sqrt(dt) * z)\n",
    "        prices.append(next_price)\n",
    "    return prices\n",
    "\n",
    "def simulate_final_prices(days: int, n_sims: int):\n",
    "    finals = []\n",
    "    for _ in range(n_sims):\n",
    "        path = simulate_prices(days)\n",
    "        finals.append(path[-1])\n",
    "    return finals\n",
    "\n",
    "def call_payoff(final_price: float, strike: float):\n",
    "    return max(final_price - strike, 0.0)\n",
    "\n",
    "def put_payoff(final_price: float, strike: float):\n",
    "    return max(strike - final_price, 0.0)\n",
    "\n",
    "def evaluate_call_price(option_price: float, finals, strike: float):\n",
    "    # Estimates E[payoff - option_price]\n",
    "    total = 0.0\n",
    "    for S_T in finals:\n",
    "        payoff = call_payoff(S_T, strike)\n",
    "        total += (payoff - option_price)\n",
    "    return total / len(finals)\n",
    "\n",
    "def evaluate_put_price(option_price: float, finals, strike: float):\n",
    "    # Estimates E[payoff - option_price]\n",
    "    total = 0.0\n",
    "    for S_T in finals:\n",
    "        payoff = put_payoff(S_T, strike)\n",
    "        total += (payoff - option_price)\n",
    "    return total / len(finals)\n",
    "\n",
    "def find_call_option_price(finals, strike: float, iterations: int = 20):\n",
    "    low, high = 0.0, 1e3  # initial bounds\n",
    "    for _ in range(iterations):\n",
    "        mid = 0.5 * (low + high)\n",
    "        value = evaluate_call_price(mid, finals, strike)\n",
    "        if value > 0:\n",
    "            low = mid\n",
    "        else:\n",
    "            high = mid\n",
    "    return 0.5 * (low + high)\n",
    "\n",
    "def find_put_option_price(finals, strike: float, iterations: int = 20):\n",
    "    low, high = 0.0, 1e3 # initial bounds\n",
    "    for _ in range(iterations):\n",
    "        mid = 0.5 * (low + high)\n",
    "        value = evaluate_put_price(mid, finals, strike)\n",
    "        if value > 0:\n",
    "            low = mid\n",
    "        else:\n",
    "            high = mid\n",
    "    return 0.5 * (low + high)\n",
    "\n",
    "def probability_call_itm(finals, strike: float):\n",
    "    count = sum(1 for S_T in finals if S_T > strike)\n",
    "    return count / len(finals)\n",
    "\n",
    "def probability_put_itm(finals, strike: float):\n",
    "    count = sum(1 for S_T in finals if S_T < strike)\n",
    "    return count / len(finals)\n",
    "\n",
    "def analyze_option(days: int, strike: int, n_sims: int, is_call: bool, print_output: bool = False):\n",
    "    finals = simulate_final_prices(days, n_sims)\n",
    "    if is_call:\n",
    "        prob = probability_call_itm(finals, strike)\n",
    "        price = find_call_option_price(finals, strike)\n",
    "    else:\n",
    "        prob = probability_put_itm(finals, strike)\n",
    "        price = find_put_option_price(finals, strike)\n",
    "    is_call_str = \"Call\" if is_call else \"Put\"\n",
    "    \n",
    "    if print_output:\n",
    "        print(f\"---\")\n",
    "        print(f\"Option: Strike {strike} {is_call_str}, {days} Days\")\n",
    "        print(f\"Probability ITM: {prob:.4f}\")\n",
    "        print(f\"Estimated option price: {price:.4f}\")\n",
    "    return prob, price"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5c5ae2a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# get ts going\n",
    "tte_list = [3 * DAYS_PER_WEEK for _ in range(8)]\n",
    "tte_list[6] -= DAYS_PER_WEEK\n",
    "tte_list[7] -= DAYS_PER_WEEK\n",
    "strike_list = [50, 50, 35, 40, 45, 60, 50, 50]\n",
    "is_call_list = [False, True, False, False, False, True, False, True]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "109a9e62",
   "metadata": {},
   "outputs": [],
   "source": [
    "# normal option analysis, no exotic shit yet\n",
    "\n",
    "# SIMS = 500000\n",
    "# for i in range(8):\n",
    "#     analyze_option(tte_list[i], strike_list[i], SIMS, is_call_list[i])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7104cd6e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# only the 2 week options seem mispriced... but there's no way to get a distribution!\n",
    "\n",
    "import numpy as np\n",
    "from statistics import NormalDist\n",
    "\n",
    "def get_distr(days: int, strike: int, m_sims: int, n_sims: int, is_call: bool):\n",
    "    probs = np.array([])\n",
    "    prices = np.array([])\n",
    "    for _ in range(m_sims):\n",
    "        prob, price = analyze_option(days, strike, n_sims, is_call)\n",
    "        probs = np.append(probs, prob)\n",
    "        prices = np.append(prices, price)\n",
    "    return probs.mean(), probs.std(), prices.mean(), prices.std()\n",
    "\n",
    "def price_conf_int(days: int, strike: int, m_sims: int, n_sims: int, is_call: bool, conf: float, print_output: bool = False):\n",
    "    _, _, s_mean, s_std = get_distr(days, strike, m_sims, n_sims, is_call)\n",
    "    z_score = NormalDist().inv_cdf(conf + (1 - conf) / 2)\n",
    "    is_call_str = \"Call\" if is_call else \"Put\"\n",
    "    low = s_mean - z_score * s_std\n",
    "    high = s_mean + z_score * s_std\n",
    "    \n",
    "    if print_output:\n",
    "        print(f\"---\")\n",
    "        print(f\"Option: Strike {strike} {is_call_str}, {days} Days\")\n",
    "        print(f\"Low:  {low}\")\n",
    "        print(f\"High: {high}\")\n",
    "    return low, high"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b7c3fcc5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# there's market type shit\n",
    "bids = [12, 12, 4.33, 6.5, 9.05, 8.8, 9.7, 9.7]\n",
    "asks = [12.05, 12.05, 4.35, 6.55, 9.1, 8.85, 9.75, 9.75]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "a432f94d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "---\n",
      "Option 0\n",
      "12.0323, 0.415\n",
      "0.469, 0.483\n",
      "---\n",
      "Option 1\n",
      "11.985, 0.8547\n",
      "0.507, 0.4697\n",
      "---\n",
      "Option 2\n",
      "4.3258, 0.2311\n",
      "0.5073, 0.4582\n",
      "---\n",
      "Option 3\n",
      "6.5202, 0.2824\n",
      "0.4715, 0.458\n",
      "---\n",
      "Option 4\n",
      "9.0952, 0.3066\n",
      "0.4413, 0.4938\n",
      "---\n",
      "Option 5\n",
      "8.7208, 0.771\n",
      "0.5409, 0.4335\n",
      "---\n",
      "Option 6\n",
      "9.8876, 0.3369\n",
      "0.2888, 0.6585\n",
      "---\n",
      "Option 7\n",
      "9.8712, 0.6175\n",
      "0.3908, 0.5778\n"
     ]
    }
   ],
   "source": [
    "M_SIMS = 200\n",
    "N_SIMS = 1000\n",
    "\n",
    "for i in range(8):\n",
    "    _, _, s_mean, s_std = get_distr(tte_list[i], strike_list[i], M_SIMS, N_SIMS, is_call_list[i])\n",
    "    target_bid, target_ask = bids[i], asks[i]\n",
    "    low_z = (target_bid - s_mean) / s_std\n",
    "    high_z = (target_ask - s_mean) / s_std\n",
    "    low_prob = NormalDist().cdf(low_z)\n",
    "    high_prob = 1 - NormalDist().cdf(high_z)\n",
    "\n",
    "    print(f\"---\")\n",
    "    print(f\"Option {i}\")\n",
    "    print(f\"{round(s_mean, 4)}, {round(s_std, 4)}\")\n",
    "    print(f\"{round(low_prob, 4)}, {round(high_prob, 4)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "5a0d6d1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# to figure out Kelly betting, we gotta get avg z-score above / below a threshold\n",
    "\n",
    "def expected_below_normal(z_th: float, sims: int):\n",
    "    z_lower_area = NormalDist().cdf(z_th)\n",
    "    trials = np.array([])\n",
    "    for _ in range(sims):\n",
    "        rand_area = np.random.uniform(0, z_lower_area)\n",
    "        rand_z = NormalDist().inv_cdf(rand_area)\n",
    "        trials = np.append(trials, rand_z)\n",
    "    return trials.mean()\n",
    "\n",
    "def expected_above_normal(z_th: float, sims: int):\n",
    "    z_upper_area = 1 - NormalDist().cdf(z_th)\n",
    "    trials = np.array([])\n",
    "    for _ in range(sims):\n",
    "        rand_area = np.random.uniform(0, z_upper_area)\n",
    "        rand_z = -NormalDist().inv_cdf(rand_area)\n",
    "        trials = np.append(trials, rand_z)\n",
    "    return trials.mean()\n",
    "\n",
    "def kelly(p: float, a: float, b: float):\n",
    "    return p/a - (1-p)/b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "40cb616d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "---\n",
      "Option 6\n",
      "Parameters: 0.6568, 0.0219, 0.0315\n",
      "Kelly bet: 19.0662\n",
      "---\n",
      "Option 7\n",
      "Parameters: 0.5793, 0.0468, 0.0571\n",
      "Kelly bet: 5.0141\n"
     ]
    }
   ],
   "source": [
    "M_SIMS = 200\n",
    "N_SIMS = 1000\n",
    "Z_SIMS = 10000\n",
    "\n",
    "for i in [6, 7]:\n",
    "    _, _, s_mean, s_std = get_distr(tte_list[i], strike_list[i], M_SIMS, N_SIMS, is_call_list[i])\n",
    "    target_bid, target_ask = bids[i], asks[i]\n",
    "    low_z = (target_bid - s_mean) / s_std\n",
    "    high_z = (target_ask - s_mean) / s_std\n",
    "    \n",
    "    above_ev = expected_above_normal(high_z, Z_SIMS) * s_std + s_mean\n",
    "    below_ev = expected_below_normal(high_z, Z_SIMS) * s_std + s_mean\n",
    "    ask = asks[i]\n",
    "    \n",
    "    p = 1 - NormalDist().cdf(high_z)\n",
    "    a = (ask - below_ev) / ask\n",
    "    b = (above_ev - ask) / ask\n",
    "    k = kelly(p, a, b)\n",
    "\n",
    "    print(f\"---\")\n",
    "    print(f\"Option {i}\")\n",
    "    print(f\"Parameters: {round(p, 4)}, {round(a, 4)}, {round(b, 4)}\")\n",
    "    print(f\"Kelly bet: {round(k, 4)}\")\n",
    "\n",
    "# kelly bets are ~20 and ~4-5, which seems odd..."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "7a0fdcd4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ok chatgpt type shi\n",
    "\n",
    "from copy import deepcopy\n",
    "\n",
    "def compute_kelly(days: int, strike: int, m_sims: int, n_sims: int, is_call: bool, price: float, print_output: bool = False):\n",
    "    finals = simulate_final_prices(days, n_sims)\n",
    "    returns = [(max(S_T - strike, 0) - price) / price for S_T in finals]\n",
    "\n",
    "    def objective(f: float):\n",
    "        copy_returns = deepcopy(returns)\n",
    "        return np.mean(np.log(1 + f * np.array(copy_returns)))\n",
    "    \n",
    "    answers = np.array([])\n",
    "    for _ in range(m_sims):\n",
    "        fs = np.linspace(0, 1, 1000)  # cap at 100% bankroll for sanity\n",
    "        vals = [objective(f) for f in fs]\n",
    "        final_answer = fs[np.argmax(vals)]\n",
    "        answers = np.append(answers, final_answer)\n",
    "    \n",
    "    kelly = answers.mean()\n",
    "    is_call_str = \"Call\" if is_call else \"Put\"\n",
    "    if print_output:\n",
    "        print(f\"---\")\n",
    "        print(f\"Option: Strike {strike} {is_call_str}, {days} Days\")\n",
    "        print(f\"Kelly Bet: {round(kelly, 6)}\")\n",
    "    \n",
    "    return kelly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "8694424d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ishaa\\AppData\\Local\\Temp\\ipykernel_10552\\2131539941.py:11: RuntimeWarning: divide by zero encountered in log\n",
      "  return np.mean(np.log(1 + f * np.array(copy_returns)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "---\n",
      "Option: Strike 50 Put, 10 Days\n",
      "Kelly Bet: 0.0\n",
      "---\n",
      "Option: Strike 50 Call, 10 Days\n",
      "Kelly Bet: 0.011011\n"
     ]
    }
   ],
   "source": [
    "M_SIMS = 100\n",
    "N_SIMS = 1000\n",
    "\n",
    "for i in [6, 7]:\n",
    "    compute_kelly(tte_list[i], strike_list[i], M_SIMS, N_SIMS, is_call_list[i], asks[i], True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
